-- MySQL Script generated by MySQL Workbench
-- lun 23 jun 2025 22:23:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shemaBC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shemaBC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shemaBC` ;
USE `shemaBC` ;

-- -----------------------------------------------------
-- Table `shemaBC`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shemaBC`.`users` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shemaBC`.`social_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shemaBC`.`social_media` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `clase` VARCHAR(45) NULL,
  `unicode` VARCHAR(45) NULL,
  `publicado` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  CONSTRAINT `fk_social_media_1`
    FOREIGN KEY (`id`)
    REFERENCES `shemaBC`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shemaBC`.`site_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shemaBC`.`site_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `config_key` VARCHAR(45) NULL,
  `config_value` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_site_config_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_site_config_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shemaBC`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shemaBC`.`articulos_de_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shemaBC`.`articulos_de_post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `contenido` LONGTEXT NULL,
  `autor` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_articulos_de_post_1`
    FOREIGN KEY (`id`)
    REFERENCES `shemaBC`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shemaBC`.`paginas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shemaBC`.`paginas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `ruta_url` VARCHAR(250) NULL,
  `subida_por_user` VARCHAR(45) NULL,
  `fecha_subida` DATETIME NULL,
  `publicada` TINYINT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_paginas_1`
    FOREIGN KEY (`id`)
    REFERENCES `shemaBC`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
