-- MySQL Script generated by MySQL Workbench
-- lun 23 jun 2025 03:25:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shemaBC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shemaBC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shemaBC` ;
USE `shemaBC` ;

-- -----------------------------------------------------
-- Table `shemaBC`.`social_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shemaBC`.`social_media` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `clase` VARCHAR(45) NULL,
  `unicode` VARCHAR(45) NULL,
  `publicado` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shemaBC`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shemaBC`.`users` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shemaBC`.`site_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shemaBC`.`site_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `config_key` VARCHAR(45) NULL,
  `config_value` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
